/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCommerceRouteImport } from './routes/admin.commerce'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin.catalog.index'
import { Route as AdminCatalogAttributesRouteImport } from './routes/admin.catalog.attributes'
import { Route as AdminCatalogCategoriesRouteImport } from './routes/admin.catalog.categories'
import { Route as AdminCatalogProductsRouteImport } from './routes/admin.catalog.products'
import { Route as AdminContentMediaRouteImport } from './routes/admin.content.media'
import { Route as AdminWebsiteIndexRouteImport } from './routes/admin.website.index'
import { Route as AdminWebsiteNavigationRouteImport } from './routes/admin.website.navigation'
import { Route as AdminWebsitePagesRouteImport } from './routes/admin.website.pages'
import { Route as StoreStoreSlugPageSlugRouteImport } from './routes/store.$storeSlug.$pageSlug'
import { Route as StoreStoreSlugCategoryCategorySlugRouteImport } from './routes/store.$storeSlug.category.$categorySlug'
import { Route as StoreStoreSlugProductProductSlugRouteImport } from './routes/store.$storeSlug.product.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommerceRoute = AdminCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogAttributesRoute = AdminCatalogAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogCategoriesRoute = AdminCatalogCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogProductsRoute = AdminCatalogProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminContentMediaRoute = AdminContentMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminWebsiteIndexRoute = AdminWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteNavigationRoute = AdminWebsiteNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsitePagesRoute = AdminWebsitePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const StoreStoreSlugPageSlugRoute = StoreStoreSlugPageSlugRouteImport.update({
  id: '/store/$storeSlug/$pageSlug',
  path: '/store/$storeSlug/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreSlugCategoryCategorySlugRoute =
  StoreStoreSlugCategoryCategorySlugRouteImport.update({
    id: '/store/$storeSlug/category/$categorySlug',
    path: '/store/$storeSlug/category/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoreStoreSlugProductProductSlugRoute =
  StoreStoreSlugProductProductSlugRouteImport.update({
    id: '/store/$storeSlug/product/$productSlug',
    path: '/store/$storeSlug/product/$productSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/store/$storeSlug/category/$categorySlug': typeof StoreStoreSlugCategoryCategorySlugRoute
  '/store/$storeSlug/product/$productSlug': typeof StoreStoreSlugProductProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/admin/website': typeof AdminWebsiteIndexRoute
  '/store/$storeSlug/category/$categorySlug': typeof StoreStoreSlugCategoryCategorySlugRoute
  '/store/$storeSlug/product/$productSlug': typeof StoreStoreSlugProductProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/content/media': typeof AdminContentMediaRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/website/': typeof AdminWebsiteIndexRoute
  '/store/$storeSlug/category/$categorySlug': typeof StoreStoreSlugCategoryCategorySlugRoute
  '/store/$storeSlug/product/$productSlug': typeof StoreStoreSlugProductProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/admin/catalog'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/website'
    | '/auth/accept-invite'
    | '/auth/reset-password'
    | '/admin/'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/content/media'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog/'
    | '/admin/website/'
    | '/store/$storeSlug/category/$categorySlug'
    | '/store/$storeSlug/product/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/reset-password'
    | '/admin'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/content/media'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog'
    | '/admin/website'
    | '/store/$storeSlug/category/$categorySlug'
    | '/store/$storeSlug/product/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/admin/catalog'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/admin/website'
    | '/auth/accept-invite'
    | '/auth/reset-password'
    | '/admin/'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/content/media'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog/'
    | '/admin/website/'
    | '/store/$storeSlug/category/$categorySlug'
    | '/store/$storeSlug/product/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  StoreStoreSlugPageSlugRoute: typeof StoreStoreSlugPageSlugRoute
  StoreStoreSlugCategoryCategorySlugRoute: typeof StoreStoreSlugCategoryCategorySlugRoute
  StoreStoreSlugProductProductSlugRoute: typeof StoreStoreSlugProductProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commerce': {
      id: '/admin/commerce'
      path: '/commerce'
      fullPath: '/admin/commerce'
      preLoaderRoute: typeof AdminCommerceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/attributes': {
      id: '/admin/catalog/attributes'
      path: '/attributes'
      fullPath: '/admin/catalog/attributes'
      preLoaderRoute: typeof AdminCatalogAttributesRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/categories': {
      id: '/admin/catalog/categories'
      path: '/categories'
      fullPath: '/admin/catalog/categories'
      preLoaderRoute: typeof AdminCatalogCategoriesRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/products': {
      id: '/admin/catalog/products'
      path: '/products'
      fullPath: '/admin/catalog/products'
      preLoaderRoute: typeof AdminCatalogProductsRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/content/media': {
      id: '/admin/content/media'
      path: '/media'
      fullPath: '/admin/content/media'
      preLoaderRoute: typeof AdminContentMediaRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/website/': {
      id: '/admin/website/'
      path: '/'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminWebsiteIndexRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/navigation': {
      id: '/admin/website/navigation'
      path: '/navigation'
      fullPath: '/admin/website/navigation'
      preLoaderRoute: typeof AdminWebsiteNavigationRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/pages': {
      id: '/admin/website/pages'
      path: '/pages'
      fullPath: '/admin/website/pages'
      preLoaderRoute: typeof AdminWebsitePagesRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/store/$storeSlug/$pageSlug': {
      id: '/store/$storeSlug/$pageSlug'
      path: '/store/$storeSlug/$pageSlug'
      fullPath: '/store/$storeSlug/$pageSlug'
      preLoaderRoute: typeof StoreStoreSlugPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeSlug/category/$categorySlug': {
      id: '/store/$storeSlug/category/$categorySlug'
      path: '/store/$storeSlug/category/$categorySlug'
      fullPath: '/store/$storeSlug/category/$categorySlug'
      preLoaderRoute: typeof StoreStoreSlugCategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeSlug/product/$productSlug': {
      id: '/store/$storeSlug/product/$productSlug'
      path: '/store/$storeSlug/product/$productSlug'
      fullPath: '/store/$storeSlug/product/$productSlug'
      preLoaderRoute: typeof StoreStoreSlugProductProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCatalogRouteChildren {
  AdminCatalogAttributesRoute: typeof AdminCatalogAttributesRoute
  AdminCatalogCategoriesRoute: typeof AdminCatalogCategoriesRoute
  AdminCatalogProductsRoute: typeof AdminCatalogProductsRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogAttributesRoute: AdminCatalogAttributesRoute,
  AdminCatalogCategoriesRoute: AdminCatalogCategoriesRoute,
  AdminCatalogProductsRoute: AdminCatalogProductsRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminContentRouteChildren {
  AdminContentMediaRoute: typeof AdminContentMediaRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentMediaRoute: AdminContentMediaRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminWebsiteRouteChildren {
  AdminWebsiteNavigationRoute: typeof AdminWebsiteNavigationRoute
  AdminWebsitePagesRoute: typeof AdminWebsitePagesRoute
  AdminWebsiteIndexRoute: typeof AdminWebsiteIndexRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteNavigationRoute: AdminWebsiteNavigationRoute,
  AdminWebsitePagesRoute: AdminWebsitePagesRoute,
  AdminWebsiteIndexRoute: AdminWebsiteIndexRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminCommerceRoute: typeof AdminCommerceRoute
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminCommerceRoute: AdminCommerceRoute,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  StoreStoreSlugPageSlugRoute: StoreStoreSlugPageSlugRoute,
  StoreStoreSlugCategoryCategorySlugRoute:
    StoreStoreSlugCategoryCategorySlugRoute,
  StoreStoreSlugProductProductSlugRoute: StoreStoreSlugProductProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
