/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCommerceRouteImport } from './routes/admin.commerce'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin.catalog.index'
import { Route as AdminCatalogAttributesRouteImport } from './routes/admin.catalog.attributes'
import { Route as AdminCatalogCategoriesRouteImport } from './routes/admin.catalog.categories'
import { Route as AdminCatalogProductsRouteImport } from './routes/admin.catalog.products'
import { Route as AdminWebsiteNavigationRouteImport } from './routes/admin.website.navigation'
import { Route as AdminWebsitePagesRouteImport } from './routes/admin.website.pages'
import { Route as StoreStoreSlugPageSlugRouteImport } from './routes/store.$storeSlug.$pageSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommerceRoute = AdminCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogAttributesRoute = AdminCatalogAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogCategoriesRoute = AdminCatalogCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogProductsRoute = AdminCatalogProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminWebsiteNavigationRoute = AdminWebsiteNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsitePagesRoute = AdminWebsitePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const StoreStoreSlugPageSlugRoute = StoreStoreSlugPageSlugRouteImport.update({
  id: '/store/$storeSlug/$pageSlug',
  path: '/store/$storeSlug/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/commerce': typeof AdminCommerceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/attributes': typeof AdminCatalogAttributesRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/admin/catalog/products': typeof AdminCatalogProductsRoute
  '/admin/website/navigation': typeof AdminWebsiteNavigationRoute
  '/admin/website/pages': typeof AdminWebsitePagesRoute
  '/store/$storeSlug/$pageSlug': typeof StoreStoreSlugPageSlugRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/catalog'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/website'
    | '/admin/'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/website'
    | '/admin'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/catalog'
    | '/admin/commerce'
    | '/admin/content'
    | '/admin/preview'
    | '/admin/settings'
    | '/admin/website'
    | '/admin/'
    | '/admin/catalog/attributes'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/website/navigation'
    | '/admin/website/pages'
    | '/store/$storeSlug/$pageSlug'
    | '/admin/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StoreStoreSlugPageSlugRoute: typeof StoreStoreSlugPageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commerce': {
      id: '/admin/commerce'
      path: '/commerce'
      fullPath: '/admin/commerce'
      preLoaderRoute: typeof AdminCommerceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/attributes': {
      id: '/admin/catalog/attributes'
      path: '/attributes'
      fullPath: '/admin/catalog/attributes'
      preLoaderRoute: typeof AdminCatalogAttributesRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/categories': {
      id: '/admin/catalog/categories'
      path: '/categories'
      fullPath: '/admin/catalog/categories'
      preLoaderRoute: typeof AdminCatalogCategoriesRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/products': {
      id: '/admin/catalog/products'
      path: '/products'
      fullPath: '/admin/catalog/products'
      preLoaderRoute: typeof AdminCatalogProductsRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/website/navigation': {
      id: '/admin/website/navigation'
      path: '/navigation'
      fullPath: '/admin/website/navigation'
      preLoaderRoute: typeof AdminWebsiteNavigationRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/pages': {
      id: '/admin/website/pages'
      path: '/pages'
      fullPath: '/admin/website/pages'
      preLoaderRoute: typeof AdminWebsitePagesRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/store/$storeSlug/$pageSlug': {
      id: '/store/$storeSlug/$pageSlug'
      path: '/store/$storeSlug/$pageSlug'
      fullPath: '/store/$storeSlug/$pageSlug'
      preLoaderRoute: typeof StoreStoreSlugPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCatalogRouteChildren {
  AdminCatalogAttributesRoute: typeof AdminCatalogAttributesRoute
  AdminCatalogCategoriesRoute: typeof AdminCatalogCategoriesRoute
  AdminCatalogProductsRoute: typeof AdminCatalogProductsRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogAttributesRoute: AdminCatalogAttributesRoute,
  AdminCatalogCategoriesRoute: AdminCatalogCategoriesRoute,
  AdminCatalogProductsRoute: AdminCatalogProductsRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminWebsiteRouteChildren {
  AdminWebsiteNavigationRoute: typeof AdminWebsiteNavigationRoute
  AdminWebsitePagesRoute: typeof AdminWebsitePagesRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteNavigationRoute: AdminWebsiteNavigationRoute,
  AdminWebsitePagesRoute: AdminWebsitePagesRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminCommerceRoute: typeof AdminCommerceRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminCommerceRoute: AdminCommerceRoute,
  AdminContentRoute: AdminContentRoute,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StoreStoreSlugPageSlugRoute: StoreStoreSlugPageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
